[package]
name = "rusty_demo"
version = "0.1.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
edition = "2021"
publish = false

[[bin]]
name = "rusty_demo"
path = "src/main.rs"

[[bin]]
name = "pi_sequential"
path = "src/pi_sequential.rs"

[[bin]]
name = "matrix_multiplcation"
path = "src/matrix_multiplication.rs"

[dependencies]
rayon = "1.5"
num_cpus = "1.13"

[target.'cfg(target_os = "hermit")'.dependencies.hermit-sys]
path = "../../hermit-sys"
default-features = false

[target.'cfg(target_arch = "aarch64")'.dependencies.aarch64]
version = "0.0.10"
default-features = false

[features]
default = ["pci", "acpi", "smp", "fs"]
vga = ["hermit-sys/vga"]
pci = ["hermit-sys/pci"]
fs = ["hermit-sys/fs"]
acpi = ["hermit-sys/acpi"]
pci-ids = ["hermit-sys/pci-ids"]
fsgsbase = ["hermit-sys/fsgsbase"]
smp = ["hermit-sys/smp"]
instrument = ["hermit-sys/instrument"]
